# Load the data

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory
dirpath = 'Dataset/'
import os
for dirname, _, filenames in os.walk(dirpath):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import mlflow

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

Dataset/offers_cluj-napoca_2022-03-25.csv

ModuleNotFoundError: No module named 'mlflow'

In [2]:
## import libraries

import pandas as pd
import numpy as np

import pickle5 as pickle
import datetime as dt
from sklearn.preprocessing import LabelEncoder

ModuleNotFoundError: No module named 'pickle5'

In [3]:
df = pd.read_csv(dirpath+"/offers_cluj-napoca_2022-03-25.csv")  # Reading dataset
df

     bathrooms  floor  rooms  surface     state            zone  ad_price
0          1.0  0.500    2.0     82.0       nou         Marasti     750.0
1          1.0  0.250    2.0     65.0  utilizat         Oasului     350.0
2          1.0  0.000    2.0     72.0       nou        Manastur     372.0
3          1.0  0.333    2.0     65.0   renovat        Ploiesti     470.0
4          1.0  2.000    2.0     45.0       nou   Dambul Rotund     290.0
..         ...    ...    ...      ...       ...             ...       ...
848        1.0  0.250    1.0     45.0   renovat   Teodor Mihali     360.0
849        2.0  0.000    3.0     85.0   renovat    Intre Lacuri     700.0
850        1.0  0.600    2.0     60.0       nou         Zorilor     480.0
851        1.0  1.000    2.0     57.0   renovat  Liviu Rebreanu     300.0
852        1.0  0.667    2.0     68.0   renovat     Cluj-Napoca     699.0

[853 rows x 7 columns]

# Exploratory Data Analysis

In [5]:
def preprocessing(df):
 
    '''
    #extract data
    df["date"]= pd.to_datetime(df["date"])
    df["day"] = df["date"].dt.day
    df["month"] = df["date"].dt.month
    df["year"] = df["date"].dt.year
    df = df.drop(columns=["date"])

    #set types
    df["price"]= df["price"].astype("int64")
    df["bedrooms"]= df["bedrooms"].astype("int64")
    df["bathrooms"]= df["bathrooms"].astype("int64")
    df["floors"]= df["floors"].astype("int64")

    #define binary features
    df["basement"] = ["No" if i == 0 else "Yes" for i in df["sqft_basement"]]
    df["situation"] = ["Former" if i <= 1990 else "New" for i in df["yr_built"]]
    df["renewal_status"] = ["Not_renewed" if i == 0 else "Renewed" for i in df["yr_renovated"]]
    '''

    #convert categorical to numerical
    lb = LabelEncoder()
    cat_variable = df.dtypes==object
    cat_variable = df.columns[cat_variable].tolist()
    df[cat_variable] = df[cat_variable].apply(lambda col: lb.fit_transform(col.astype(str)))

    return df   

df = preprocessing(df)
df.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,...,street,city,statezip,country,day,month,year,basement,situation,renewal_status
count,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,...,4600.000000,4600.000000,4600.000000,4600.0,4600.000000,4600.000000,4600.0,4600.000000,4600.000000,4600.000000
mean,5.519630e+05,3.400870,1.788913,2139.346957,1.485252e+04,1.459130,0.007174,0.240652,3.451739,1827.265435,...,2265.385870,25.674348,38.743696,0.0,14.791304,5.757609,2014.0,0.403261,0.311957,0.405435
std,5.638347e+05,0.908848,0.752185,963.206916,3.588444e+04,0.552194,0.084404,0.778405,0.677230,862.168977,...,1307.591795,11.982721,20.919517,0.0,8.677569,0.683851,0.0,0.490606,0.463343,0.491029
min,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,...,0.000000,0.000000,0.000000,0.0,1.000000,5.000000,2014.0,0.000000,0.000000,0.000000
25%,3.228750e+05,3.000000,1.000000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,...,1132.750000,17.000000,21.000000,0.0,7.000000,5.000000,2014.0,0.000000,0.000000,0.000000
50%,4.609430e+05,3.000000,2.000000,1980.000000,7.683000e+03,1.000000,0.000000,0.000000,3.000000,1590.000000,...,2263.500000,32.000000,41.000000,0.0,14.000000,6.000000,2014.0,0.000000,0.000000,0.000000
75%,6.549625e+05,4.000000,2.000000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,...,3400.250000,35.000000,56.000000,0.0,23.000000,6.000000,2014.0,1.000000,1.000000,1.000000
max,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.000000,1.000000,4.000000,5.000000,9410.000000,...,4524.000000,43.000000,76.000000,0.0,31.000000,7.000000,2014.0,1.000000,1.000000,1.000000

In [6]:
def eliminate_outliers(df):
    Q1 = df.quantile(0.25)
    Q3 = df.quantile(0.75)
    IQR = Q3 - Q1
    df =df[~((df < (Q1 - 1.5 * IQR)) |(df > (Q3 + 1.5 * IQR))).any(axis=1)]
    df.dropna(inplace=True)
    return df

df = eliminate_outliers(df)
df.describe()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,...,street,city,statezip,country,day,month,year,basement,situation,renewal_status
count,3.457000e+03,3457.000000,3457.000000,3457.000000,3457.000000,3457.000000,3457.0,3457.0,3457.000000,3457.000000,...,3457.000000,3457.000000,3457.000000,3457.0,3457.000000,3457.000000,3457.0,3457.000000,3457.000000,3457.000000
mean,4.548180e+05,3.292161,1.660110,1889.322823,7207.278565,1.446630,0.0,0.0,3.446919,1645.998264,...,2252.479896,25.929129,39.221579,0.0,14.723460,5.759329,2014.0,0.365346,0.322534,0.403529
std,1.994033e+05,0.782276,0.605633,671.350427,3598.448641,0.560155,0.0,0.0,0.662860,667.785149,...,1334.127576,11.649686,20.817843,0.0,8.659947,0.682910,0.0,0.481597,0.467514,0.490676
min,0.000000e+00,2.000000,0.000000,580.000000,681.000000,1.000000,0.0,0.0,2.000000,580.000000,...,0.000000,0.000000,0.000000,0.0,1.000000,5.000000,2014.0,0.000000,0.000000,0.000000
25%,3.040000e+05,3.000000,1.000000,1380.000000,4738.000000,1.000000,0.0,0.0,3.000000,1140.000000,...,1071.000000,18.000000,22.000000,0.0,7.000000,5.000000,2014.0,0.000000,0.000000,0.000000
50%,4.250000e+05,3.000000,2.000000,1820.000000,7200.000000,1.000000,0.0,0.0,3.000000,1460.000000,...,2252.000000,32.000000,42.000000,0.0,14.000000,6.000000,2014.0,0.000000,0.000000,0.000000
75%,5.719860e+05,4.000000,2.000000,2320.000000,9260.000000,2.000000,0.0,0.0,4.000000,2040.000000,...,3434.000000,35.000000,57.000000,0.0,23.000000,6.000000,2014.0,1.000000,1.000000,1.000000
max,1.150000e+06,5.000000,3.000000,4140.000000,20000.000000,3.000000,0.0,0.0,5.000000,3960.000000,...,4524.000000,43.000000,76.000000,0.0,31.000000,7.000000,2014.0,1.000000,1.000000,1.000000

In [7]:
df.info() # looking at information

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3457 entries, 0 to 4599
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   price           3457 non-null   int64
 1   bedrooms        3457 non-null   int64
 2   bathrooms       3457 non-null   int64
 3   sqft_living     3457 non-null   int64
 4   sqft_lot        3457 non-null   int64
 5   floors          3457 non-null   int64
 6   waterfront      3457 non-null   int64
 7   view            3457 non-null   int64
 8   condition       3457 non-null   int64
 9   sqft_above      3457 non-null   int64
 10  sqft_basement   3457 non-null   int64
 11  yr_built        3457 non-null   int64
 12  yr_renovated    3457 non-null   int64
 13  street          3457 non-null   int64
 14  city            3457 non-null   int64
 15  statezip        3457 non-null   int64
 16  country         3457 non-null   int64
 17  day             3457 non-null   int64
 18  month           3457 non-null   int64
 19  year            3457 non-null   int64
 20  basement        3457 non-null   int64
 21  situation       3457 non-null   int64
 22  renewal_status  3457 non-null   int64
dtypes: int64(23)
memory usage: 648.2 KB

In [8]:
df.describe()  # looking at statistical info

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,...,street,city,statezip,country,day,month,year,basement,situation,renewal_status
count,3.457000e+03,3457.000000,3457.000000,3457.000000,3457.000000,3457.000000,3457.0,3457.0,3457.000000,3457.000000,...,3457.000000,3457.000000,3457.000000,3457.0,3457.000000,3457.000000,3457.0,3457.000000,3457.000000,3457.000000
mean,4.548180e+05,3.292161,1.660110,1889.322823,7207.278565,1.446630,0.0,0.0,3.446919,1645.998264,...,2252.479896,25.929129,39.221579,0.0,14.723460,5.759329,2014.0,0.365346,0.322534,0.403529
std,1.994033e+05,0.782276,0.605633,671.350427,3598.448641,0.560155,0.0,0.0,0.662860,667.785149,...,1334.127576,11.649686,20.817843,0.0,8.659947,0.682910,0.0,0.481597,0.467514,0.490676
min,0.000000e+00,2.000000,0.000000,580.000000,681.000000,1.000000,0.0,0.0,2.000000,580.000000,...,0.000000,0.000000,0.000000,0.0,1.000000,5.000000,2014.0,0.000000,0.000000,0.000000
25%,3.040000e+05,3.000000,1.000000,1380.000000,4738.000000,1.000000,0.0,0.0,3.000000,1140.000000,...,1071.000000,18.000000,22.000000,0.0,7.000000,5.000000,2014.0,0.000000,0.000000,0.000000
50%,4.250000e+05,3.000000,2.000000,1820.000000,7200.000000,1.000000,0.0,0.0,3.000000,1460.000000,...,2252.000000,32.000000,42.000000,0.0,14.000000,6.000000,2014.0,0.000000,0.000000,0.000000
75%,5.719860e+05,4.000000,2.000000,2320.000000,9260.000000,2.000000,0.0,0.0,4.000000,2040.000000,...,3434.000000,35.000000,57.000000,0.0,23.000000,6.000000,2014.0,1.000000,1.000000,1.000000
max,1.150000e+06,5.000000,3.000000,4140.000000,20000.000000,3.000000,0.0,0.0,5.000000,3960.000000,...,4524.000000,43.000000,76.000000,0.0,31.000000,7.000000,2014.0,1.000000,1.000000,1.000000

# Modelling

Let's start the model!

In [9]:
from sklearn.metrics import mean_squared_error

In [10]:
#X = df.drop(columns=["price","view","waterfront","country", "year", "situation","basement","renewal_status"])
X = df[['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'sqft_above', 'sqft_basement', 'floors', 'waterfront', 'view', 'yr_built', 'yr_renovated', 'city', 'country', 'renewal_status']]
y = df["price"]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2)

In [33]:
import os
import warnings
import sys

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import ElasticNet
from urllib.parse import urlparse
import mlflow
import mlflow.sklearn
from mlflow.models.signature import infer_signature


import logging

logging.basicConfig(level=logging.WARN)
logger = logging.getLogger(__name__)


def eval_metrics(actual, pred):
    rmse = np.sqrt(mean_squared_error(actual, pred))
    mae = mean_absolute_error(actual, pred)
    r2 = r2_score(actual, pred)
    return rmse, mae, r2


#if __name__ == "__main__":
warnings.filterwarnings("ignore")
np.random.seed(40)


alpha = 0.5       #float(sys.argv[1]) if len(sys.argv) > 1 else 0.5
l1_ratio = 0.9   #float(sys.argv[2]) if len(sys.argv) > 2 else 0.5


def mlflow_fit_eval(model, name='', train_x=X_train, train_y=y_train, test_x=X_test, test_y=y_test):
    with mlflow.start_run(run_name=name):
        mlflow.autolog()
        model.fit(train_x, train_y)
        predicted_qualities = model.predict(test_x)

        (rmse, mae, r2) = eval_metrics(test_y, predicted_qualities)

        print('\n\n',name)
        print("  RMSE: %s" % rmse)
        print("  MAE: %s" % mae)
        print("  R2: %s" % r2)

        mlflow.log_param("alpha", alpha)
        mlflow.log_param("l1_ratio", l1_ratio)
        mlflow.log_metric("rmse", rmse)
        mlflow.log_metric("r2", r2)
        mlflow.log_metric("mae", mae)
       
        signature = infer_signature(test_x, predicted_qualities)
        mlflow.sklearn.log_model(model, name, signature=signature)
    return model

In [34]:
X_test.columns

Index(['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'sqft_above',
       'sqft_basement', 'floors', 'waterfront', 'view', 'yr_built',
       'yr_renovated', 'city', 'country', 'renewal_status'],
      dtype='object')

In [35]:
import sklearn
import xgboost
import lightgbm
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
   

def models():
    lr = sklearn.linear_model.LinearRegression()
    lr = mlflow_fit_eval(lr, 'LinearRegression', train_x, train_y, test_x, test_y)
    #lr.fit(X_train,y_train)
    
    knn = KNeighborsRegressor()
    knn = mlflow_fit_eval(knn, 'KNeighborsRegressor', train_x, train_y, test_x, test_y)
    #knn.fit(X_train,y_train)

    svc = sklearn.svm.SVR(kernel='linear')
    svc = mlflow_fit_eval(svc, 'SVM', train_x, train_y, test_x, test_y)
    #svc.fit(X_train,y_train)

    tree=DecisionTreeRegressor()
    tree = mlflow_fit_eval(tree, 'DecisionTreeRegressor', train_x, train_y, test_x, test_y)
    #tree.fit(X_train,y_train)

    forest = RandomForestRegressor()
    forest = mlflow_fit_eval(forest, 'RandomForestRegressor', train_x, train_y, test_x, test_y)
    #forest.fit(X_train,y_train)

    gb = GradientBoostingRegressor()
    gb = mlflow_fit_eval(gb, 'GradientBoostingRegressor', train_x, train_y, test_x, test_y)
    #gb.fit(X_train,y_train)
    
    xgb = xgboost.XGBRegressor()
    xgb = mlflow_fit_eval(xgb, 'XGBRegressor', train_x, train_y, test_x, test_y)
    #xgb.fit(X_train,y_train)

    
    lgbm = lightgbm.LGBMRegressor()
    lgbm = mlflow_fit_eval(lgbm, 'LGBMRegressor', train_x, train_y, test_x, test_y)
    #lgbm.fit(X_train,y_train)
    
    #Print the accuracy for ech model
    print("Results")
    print('[0] Logistic Regression Test Error: ',np.sqrt(mean_squared_error(y_test,lr.predict(X_test))))
    print('[1] K neighbors Regression Test Error: ',np.sqrt(mean_squared_error(y_test,knn.predict(X_test))))
    print('[2] SVR linear Regression Test Error: ',np.sqrt(mean_squared_error(y_test,svc.predict(X_test))))
    print('[3] Decision Tree Regression Test Error: ',np.sqrt(mean_squared_error(y_test,tree.predict(X_test))))
    print('[4] Random Forest Regression Test Error: ',np.sqrt(mean_squared_error(y_test,forest.predict(X_test))))
    print('[5] Gradient Boosting Regression Test Error: ',np.sqrt(mean_squared_error(y_test,gb.predict(X_test))))
    print('[6] XGBoost Regression Test Error: ',np.sqrt(mean_squared_error(y_test,xgb.predict(X_test))))
    print('[7] LightGBM Regression Test Error: ',np.sqrt(mean_squared_error(y_test,lgbm.predict(X_test)))) 

    return lr,knn,svc,tree,forest,gb,xgb,lgbm

In [36]:
lr,knn,svc,tree,forest,gb,xgb,lgbm = models()

2022/05/11 11:00:43 INFO mlflow.tracking.fluent: Autologging successfully enabled for xgboost.
2022/05/11 11:00:43 INFO mlflow.tracking.fluent: Autologging successfully enabled for lightgbm.
2022/05/11 11:00:43 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2022/05/11 11:00:45 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmp33h_zegm/model/model.pkl, flavor: sklearn), fall back to return ['scikit-learn==0.24.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.

 LinearRegression
  RMSE: 149251.53609329672
  MAE: 114146.54826440047
  R2: 0.4136803618914491

2022/05/11 11:00:46 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmp51vz5sdr/model/model.pkl, flavor: sklearn), fall back to return ['scikit-learn==0.24.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.
2022/05/11 11:00:46 INFO mlflow.tracking.fluent: Autologging successfully enabled for xgboost.
2022/05/11 11:00:46 INFO mlflow.tracking.fluent: Autologging successfully enabled for lightgbm.
2022/05/11 11:00:46 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2022/05/11 11:00:48 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmp2objjavv/model/model.pkl, flavor: sklearn), fall back to return ['scikit-learn==0.24.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.

 KNeighborsRegressor
  RMSE: 167326.84306398002
  MAE: 129381.79653179192
  R2: 0.26306691272917215

2022/05/11 11:00:49 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmpl_v0yh52/model/model.pkl, flavor: sklearn), fall back to return ['scikit-learn==0.24.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.
2022/05/11 11:00:49 INFO mlflow.tracking.fluent: Autologging successfully enabled for xgboost.
2022/05/11 11:00:49 INFO mlflow.tracking.fluent: Autologging successfully enabled for lightgbm.
2022/05/11 11:00:49 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2022/05/11 11:00:53 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmpipdr4h02/model/model.pkl, flavor: sklearn), fall back to return ['scikit-learn==0.24.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.

 SVM
  RMSE: 152904.09974333382
  MAE: 117747.23531882805
  R2: 0.38463175473318767

2022/05/11 11:00:54 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmpp40njz57/model/model.pkl, flavor: sklearn), fall back to return ['scikit-learn==0.24.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.
2022/05/11 11:00:54 INFO mlflow.tracking.fluent: Autologging successfully enabled for xgboost.
2022/05/11 11:00:54 INFO mlflow.tracking.fluent: Autologging successfully enabled for lightgbm.
2022/05/11 11:00:55 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2022/05/11 11:00:56 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmpo2wfzu6b/model/model.pkl, flavor: sklearn), fall back to return ['scikit-learn==0.24.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.

 DecisionTreeRegressor
  RMSE: 169727.7612296367
  MAE: 116602.72976878613
  R2: 0.24176716581297086

2022/05/11 11:00:57 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmpheqiwq_m/model/model.pkl, flavor: sklearn), fall back to return ['scikit-learn==0.24.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.
2022/05/11 11:00:57 INFO mlflow.tracking.fluent: Autologging successfully enabled for xgboost.
2022/05/11 11:00:57 INFO mlflow.tracking.fluent: Autologging successfully enabled for lightgbm.
2022/05/11 11:00:57 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2022/05/11 11:01:00 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmprtii_iyh/model/model.pkl, flavor: sklearn), fall back to return ['scikit-learn==0.24.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.

 RandomForestRegressor
  RMSE: 123201.39403177968
  MAE: 86197.13369942197
  R2: 0.6004896220383298

2022/05/11 11:01:02 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmppvqylndx/model/model.pkl, flavor: sklearn), fall back to return ['scikit-learn==0.24.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.
2022/05/11 11:01:02 INFO mlflow.tracking.fluent: Autologging successfully enabled for xgboost.
2022/05/11 11:01:02 INFO mlflow.tracking.fluent: Autologging successfully enabled for lightgbm.
2022/05/11 11:01:02 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2022/05/11 11:01:04 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmp5w41zgkh/model/model.pkl, flavor: sklearn), fall back to return ['scikit-learn==0.24.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.

 GradientBoostingRegressor
  RMSE: 120063.87020803189
  MAE: 85225.34041034663
  R2: 0.6205788827189745

MlflowException: Changing param values is not allowed. Param with key='alpha' was already logged with value='0.9' for run ID='a3d6d6190ed446ddbd3c2664761dc635'. Attempted logging new value '0.5'.

The cause of this error is typically due to repeated calls
to an individual run_id event logging.

Incorrect Example:
---------------------------------------
with mlflow.start_run():
    mlflow.log_param("depth", 3)
    mlflow.log_param("depth", 5)
---------------------------------------

Which will throw an MlflowException for overwriting a
logged parameter.

Correct Example:
---------------------------------------
with mlflow.start_run():
    with mlflow.start_run(nested=True):
        mlflow.log_param("depth", 3)
    with mlflow.start_run(nested=True):
        mlflow.log_param("depth", 5)
---------------------------------------

Which will create a new nested run for each individual
model and prevent parameter key collisions within the
tracking store.'

In [ ]:
import pickle5 as pickle
# save the model to disk
pickle.dump(lr, open('models/lr.sav', 'wb'))
pickle.dump(knn, open('models/knn.sav', 'wb'))
pickle.dump(svc, open('models/svc.sav', 'wb'))
pickle.dump(tree, open('models/tree.sav', 'wb'))
pickle.dump(forest, open('models/forest.sav', 'wb'))
pickle.dump(gb, open('models/gb.sav', 'wb'))
pickle.dump(xgb, open('models/xgb.sav', 'wb'))
pickle.dump(lgbm, open('models/lgbm.sav', 'wb'))

The model works best with LightGBM.

# Feature Importance

In [ ]:
Importance = pd.DataFrame({"Importance": lgbm.feature_importances_*100},
                         index = X_train.columns)

In [ ]:
Importance.sort_values(by = "Importance", 
                       axis = 0, 
                       ascending = True).plot(kind ="barh", color = "r")

plt.xlabel("Variable Severity Levels")

If you like it plase vote!